-- Cloudflare D1 schema for the calendar_events MIRROR.
-- Companion to schema.sql (transcript segments), schema_meetings.sql
-- (meeting state), and schema_meeting_owners.sql (ownership). AWS Postgres
-- (calendar-service's CalendarEvent table) remains the source of truth;
-- Google Calendar itself remains the source of truth for Postgres. This
-- table is reconciled on every calendar sync, remove, and restore — see
-- services/meeting-api/meeting_api/collector/d1_calendar_events_forwarder.py.
--
-- Apply once, e.g.:
--   wrangler d1 execute <DB_NAME> --remote --file deploy/cloudflare-d1/schema_calendar_events.sql
-- or paste into the D1 console.
--
-- `id` is the Postgres CalendarEvent primary key (not autogenerated here) so
-- the mirror's upsert (`INSERT ... ON CONFLICT (id) DO UPDATE`) is keyed on
-- the same identity as Postgres. This table is upsert-only — rows are never
-- deleted, only marked status='cancelled' — matching the fact that Postgres
-- never hard-deletes a CalendarEvent either.
--
-- start_time_ms/end_time_ms are epoch milliseconds (INTEGER), not ISO
-- strings, so range filtering (e.g. "not yet ended") is a reliable numeric
-- comparison; GET /calendar/meetings converts them back to ISO8601 UTC
-- strings when building its response.

CREATE TABLE IF NOT EXISTS calendar_events (
  id             INTEGER PRIMARY KEY,
  owner_email    TEXT,
  title          TEXT,
  start_time_ms  INTEGER,
  end_time_ms    INTEGER,
  meeting_url    TEXT,
  platform       TEXT,
  status         TEXT,
  meeting_id     INTEGER
);

-- Primary access path: "this client's calendar events, soonest first".
CREATE INDEX IF NOT EXISTS ix_calendar_events_owner_start
  ON calendar_events (owner_email, start_time_ms);
